### ISSUE TITLE
Expected Input shape?

### ISSUE THREAD

**Issue by PankajB1997** [kpot/keras-transformer#10]
Hi,
Thanks for implementing this library. For the universal GPT transformer example you provided, what is the expected input like?
For your reference, I'm trying to solve a text summarization problem and my input is an article of words. From my understanding, I need to map each word to an index and pass that as input.

So, if my input is "an apple a day keeps the doctor away", my encoded sequence will look something like [52, 34, 25, 23, 56, 12, 57, 45]

I am doing this for every article, so my input shape will be (train_set_size, max_seq_length, 1).

However, I'm getting error for this input shape. How do I fix this? 

Also, what is the expected output shape?

Thanks.

**Comment by PankajB1997** [comment]
Also, what is the expected shape for target data?

**Comment by kpot** [comment]
Hi,
the model you're talking about has this line
```python
word_ids = Input(shape=(max_seq_length,), dtype='int32', name='word_ids')
```
Its meaning is accurately described in the documentation for Keras, [right here](https://keras.io/layers/core/#input):
> **shape**: A shape tuple (integer), not including the batch size. For instance, shape=(32,) indicates that the expected input will be *batches of 32-dimensional vectors*.

Keras by default implies that all input tensors already have "batch size" as their first dimension (unless explicitly specified via `batch_shape` argument), and by default its size is variable so that you could feed to the model batches of any size you like.

So, answering your question, the input shape is `(batch_size, max_seq_length)`. Also, "batch size" is normally not the same thing as "training set size".
